### ISSUE TITLE
User registration API with OTP trigger

### ISSUE THREAD

**Issue by reehanlalkhan** [usmanazhar/NeedNet#1]
Create REST API for Sign-Up of user. Store the user details in database.
Create entry in trigger table for OTP generation of the user
Below is the sample JSON body for user sign-up.
`{
    "name":"",
    "email":"",
    "place":"",
    "age":"",
    "gender":"male/female/others",
    "occupation":""
}`

**Comment by waheeduddin1357** [comment]
completed
